name: bento_challenge
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_modular: ^6.3.4
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/fonts/
    - lib/assets/png_icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: lib/assets/fonts/nunito/Nunito-Regular.ttf
        - asset: lib/assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/nunito/Nunito-Black.ttf
          weight: 900
